name: build

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker Registry
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t mlandauer/home-dashboard:$GITHUB_SHA \
            --push \
            .
